### ISSUE TITLE
Build error on Fedora 38

### ISSUE THREAD

**Issue by poVoq** [tsl0922/pytorch-gfx803#1]
Thanks for posting this guide!

I am trying to replicate it on Fedora 38 (explicitly starting everything with pythin3.10 instead of python3) and I get the following error:

```
-- Found PythonLibs: /usr/lib64/libpython3.10.so.1.0 (Required is at least version "3.0") 
CMake Error at cmake/Dependencies.cmake:1075 (if):
  if given arguments:

    "VERSION_LESS" "3"

  Unknown arguments specified
Call Stack (most recent call first):
  CMakeLists.txt:722 (include)


-- Configuring incomplete, errors occurred!
```

Which seems to not make sense as clearly Python3.10 is being found.

If I try to run it again I only get:

```
Building wheel torch-1.13.1
-- Building version 1.13.1
cmake3 --build . --target install --config Release -- -j 12
gmake: Makefile: No such file or directory
gmake: *** No rule to make target 'Makefile'.  Stop.
```

Any idea how that might be fixable?

Thanks again.

**Comment by tsl0922** [comment]
Check [cmake/Dependencies.cmake:1075](https://github.com/pytorch/pytorch/blob/v1.13.1/cmake/Dependencies.cmake#L1073-L1075):
```
if(${PYTHONLIBS_VERSION_STRING} VERSION_LESS 3)
```

It seems `PYTHONLIBS_VERSION_STRING` is not properly set by `find_package(PythonLibs 3.0)`.

**Comment by poVoq** [comment]
Thanks that helped a bit :)

Installing `python3.10-devel` seems to have fixed this.

Next error is `ModuleNotFoundError: No module named 'typing_extensions'` which can be probably solved by installing it via pip, but is there a way to restart the process without deleting everything?

Whenever I hit some error it ends up with this when I try to run it again:

```
Building wheel torch-1.13.1
-- Building version 1.13.1
cmake3 --build . --target install --config Release -- -j 12
gmake: Makefile: No such file or directory
gmake: *** No rule to make target 'Makefile'.  Stop.
```

and so far the only way I found to fix it is to delete the entire /pytorch folder and start new.

Edit: finally got it to start building, but it has a constant stream of various errors and problems impossible to fix all. I guess I need to use an older version of gcc or so? By default it uses gcc 13 which seems to be problematic with older code? :-/

**Comment by tsl0922** [comment]
> I guess I need to use an older version of gcc or so?

use gcc 11. I've testd gcc 12 on archlinux, it doesn't work too.

EDIT: I've updated README for gcc and kernel version.

**Comment by tsl0922** [comment]
archlinux has a packaged [python-pytorch-rocm](https://archlinux.org/packages/extra/x86_64/python-pytorch-rocm/) which supports gfx803 now, you may want to reference from the package's [source](https://gitlab.archlinux.org/archlinux/packaging/packages/python-pytorch).
