### ISSUE TITLE
Missing some dependencies on Ubuntu 22.04.2

### ISSUE THREAD

**Issue by WeirdWood** [tsl0922/pytorch-gfx803#2]
Looks like the prebuilt Pytorch is depending on 2 other libraries that're not listed in the README, `libopenmpi3` and `libstdc++-12-dev`.
It works perfectly after installing these 2.

1 more small thing is that UniPC sampler will complain about missing MAGMA support:
```
RuntimeError: linalg.lu_factor: PyTorch was not compiled with MAGMA support.
```

Everything else is perfect, thanks a lot for providing the prebuilt Pytorch and the build instruction. Using the same instruction I have compiled the latest Torch v2.0.1-rc2 and confirmed that it works perfectly with ROCm 5.5.0.

**Comment by tsl0922** [comment]
Thanks, updated the release.
