### ISSUE TITLE
RX560, Arch, Community PKGs: Torch fails to use GPU

### ISSUE THREAD

**Issue by UltraBlackLinux** [tsl0922/pytorch-gfx803#3]
Hey there,
I was hoping to get this to work on my RX560 since my CPU is pretty slow. I'm hoping to get an ML performance boost out of this, but for some reason, torch still refuses to detect ROCM.

I have to admit that I'm striving a bit from the installation instructions, since I'm running arch linux, but I don't think that that makes a big difference. 
I got all the rocm packages from the official repos, which I would expect to work in this configuration (some of which are unrelated, but had them installed before, and grep just found them)
```
local/comgr 5.4.3-1
local/hip-runtime-amd 5.4.3-1
local/hipblas 5.4.3-1
local/hsa-rocr 5.4.3-1
local/rccl 5.4.3-1
local/rocalution 5.4.3-1
local/rocblas 5.4.3-2
local/rocfft 5.4.3-1
local/rocm-clang-ocl 5.4.3-1
local/rocm-cmake 5.4.3-1
local/rocm-core 5.4.3-4
local/rocm-device-libs 5.4.3-1
local/rocm-hip-libraries 5.4.3-2
local/rocm-hip-runtime 5.4.3-2
local/rocm-hip-sdk 5.4.3-2
local/rocm-language-runtime 5.4.3-2
local/rocm-llvm 5.4.3-1
local/rocm-ml-libraries 5.4.3-2
local/rocm-ml-sdk 5.4.3-2
local/rocm-opencl-runtime 5.4.3-1
local/rocm-opencl-sdk 5.4.3-2
local/rocm-smi-lib 5.4.3-1
local/rocminfo 5.4.3-1
local/rocrand 5.4.3-1
local/rocsolver 5.4.3-1
local/rocsparse 5.4.3-1
local/rocthrust 5.4.3-1
```
I installed the .whls from the releases (thank you for sharing those) and added them to the stable-diffusion-web-ui torch installation command to replace the rocm download link.
Double checking the required packages and rebooting several times all haven't helped and I still don't get any support.
I checked, my RX560 is in fact gfx803, so it should work to my knowledge.
Any idea what else I could be doing wrong?
Thanks!

Edit: After some investigation, I found an issue: The wheel package didn't install because it is incompatible with python 3.11, only 3.10 is possible. Renaming the wheel after finding that out caused the C part of pytorch to not function
I'm installing python 3.10 since building pytorch is way too much of a hassle.

Edit 2: Got that installed, but weirdly, torch now wants billions of libraries of various packages. First it wanted libroctx64.so.4, now it wants libopenblas.so.0. Since the latter wants to replace blas, I don't want to proceed unless I have full confirmation that I should do that. I wonder why it's even doing this now...
If you still have the package around, could you compile the wheel for python 3.11? Maybe set up github actions for that?

**Comment by tsl0922** [comment]
There is an AUR package for pytorch rocm already, you may want to use it instead.

**Comment by UltraBlackLinux** [comment]
Hm I can't find it though
```
∑  yay -Ss torch rocm
aur/python-torchaudio-rocm 2.0.1-1 (+2 0.87)
    Data manipulation and transformation for audio signal processing, powered by PyTorch (ROCm Support)
aur/python-torchvision-rocm 0.15.1-3 (+3 1.35)
    Datasets, transforms, and models specific to computer vision (with ROCM support)
aur/torchvision-rocm 0.15.1-3 (+3 1.35)
    Datasets, transforms, and models specific to computer vision (C++ library only, with ROCM support)
community/python-pytorch-opt-rocm 2.0.1-1 (138.5 MiB 1.4 GiB)
    Tensors and Dynamic neural networks in Python with strong GPU acceleration (with ROCm and AVX2 CPU optimizations)
community/python-pytorch-rocm 2.0.1-1 (137.5 MiB 1.4 GiB)
    Tensors and Dynamic neural networks in Python with strong GPU acceleration (with ROCm)
```
The community package is what comes the closest. I guess I could get the makefile from that and add the env variable

Edit: Oh well: https://github.com/archlinux/svntogit-community/blob/packages/python-pytorch/trunk/PKGBUILD#L263

**Comment by UltraBlackLinux** [comment]
Yep cuda is available now! only gotta figure out how I can get the venv to use the system installation
